version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /src/PublicData.Web
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ["@angular/*", "@angular-devkit/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /src/PublicData.Api
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /src/PublicData.McpServer
    schedule:
      interval: monthly
