<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Guilherme Cauã</Authors>
    <Product>Assistente de Dados Públicos</Product>
  </PropertyGroup>
</Project>
